name: bid_bazaar
description: "BidBazaar"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-105.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http_parser: ^4.0.0
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  url_launcher: ^6.3.0
  flutter_svg: ^0.23.0+1
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  file_picker: ^8.0.0+1
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware